#include <QCoreApplication>
#include <QDebug>
#include <QEvent>
#include <QLocale>
#include <QTranslator>

// Force the embedded .qm resource to be registered before we use it.
// Without this, the static init order is undefined and the resource
// may not yet exist when installTranslations() runs.
void qInitResources_caelestia_translations();   // generated by rcc

namespace {
void installTranslations()
{
    if (!qApp)
        return;

    // Ensure the Qt resource containing .qm files is initialised
    qInitResources_caelestia_translations();

    const QString locale = QLocale::system().name();
    const QString base   = QStringLiteral(":/i18n/caelestia_");
    auto *translator     = new QTranslator(qApp);

    if (translator->load(base + locale + QStringLiteral(".qm"))
        || translator->load(base + locale.left(2) + QStringLiteral(".qm"))) {
        qWarning() << "[i18n] Loaded translations for locale" << locale;
        QCoreApplication::installTranslator(translator);
        QCoreApplication::postEvent(qApp, new QEvent(QEvent::LanguageChange));
    } else {
        qWarning() << "[i18n] No translation file found for locale" << locale;
        delete translator;
    }
}

struct TranslationLoader {
    TranslationLoader() { installTranslations(); }
} s_loader;
} // namespace
